package com.biu.generate.controller;

import com.biu.common.base.controller.BaseController;
import com.biu.core.toolbox.ajax.AjaxResult;
import com.biu.core.toolbox.kit.JsonKit;
import com.biu.generate.model.Notice;
import com.biu.generate.service.NoticeService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.annotation.Resource;

/**
 * Generated by Blade.
 * 2017-03-07 15:42:08
 */
@Controller
@RequestMapping("/notice")
public class NoticeController extends BaseController {

	private static String CODE = "notice";
	private static String PREFIX = "blade_notice";
	private static String BASE_PATH = "/generate/notice/";

	@Resource
    private NoticeService noticeService;

    /**
	 * 跳转列表页
	 * @param mm
	 * @return
	 */
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "notice.html";
	}

	/**
     * 跳转新增页面
     * @param mm
     * @return
     */
	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "notice_add.html";
	}

    /**
     * 跳转修改页面
     * @return
     */
	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable Integer id, ModelMap mm) {
		Notice notice = noticeService.getOneByKey(id);
		mm.put("model", JsonKit.toJson(notice));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "notice_edit.html";
	}

    /**
     * 跳转详情页面
     * @return
     */
	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable Integer id, ModelMap mm) {
		Notice notice = noticeService.getOneByKey(id);
		mm.put("model", JsonKit.toJson(notice));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "notice_view.html";
	}

    /**
     * 返回列表数据
     * @return
     */
	@ResponseBody
    @RequestMapping(KEY_LIST)
    public Object list() {
        Object grid = paginate(PREFIX);
        return grid;
    }

    /**
	 * 新增
	 * @return
	 */
	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		Notice notice = mapping(PREFIX, Notice.class);
		int temp = noticeService.save(notice);
		if (temp > 0) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

    /**
     * 修改
     * @return
     */
	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Notice notice = mapping(PREFIX, Notice.class);
		int temp = noticeService.updateNotEmpty(notice);
		if (temp > 0) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

    /**
	 * 删除
	 * @return
	 */
	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = noticeService.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
