package com.biu.generate.service.impl;

import com.biu.common.base.service.impl.BaseServiceImpl;
import com.biu.generate.mapper.NoticeMapper;
import com.biu.generate.model.Notice;
import com.biu.generate.service.NoticeService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * Generated by Biu.
 * 2017-03-07 15:42:08
 */
@Service
public class NoticeServiceImpl extends BaseServiceImpl<Notice> implements NoticeService {

        @Resource
        private NoticeMapper noticeMapper;

}



