package com.biu.generate.model;

import java.util.Date;

import com.biu.core.annotation.BindID;
import lombok.Data;

import javax.persistence.*;

/**
 * Generated by Biu.
 * 2017-03-07 15:42:08
 */
@Table(name = "blade_notice")
@BindID(name = "id")
@Data
public class Notice {

    @Id
    @Column(name = "id")
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id; //序列
	private String title; //标题
	private Integer type; //类型
	private String content; //内容
	private Date publishtime; //发布时间
	private Date createtime; //创建时间
	private Integer creater; //创建人
	private Integer pic; //图片
	private Integer version;

}
