package com.biu.generate.service;

import java.util.Map;

import com.biu.common.base.service.BaseService;
import com.biu.generate.model.Notice;

/**
 * Generated by Biu.
 * 2017-03-07 15:42:08
 */
public interface NoticeService extends BaseService<Notice> {

}
